language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

#before_script:
  #- mysql -u root -e 'CREATE DATABASE testbase;'
  #- mysql -u root testbase < resources/testbase.sql
  
script: 
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
